language: node_js

node_js:
  - 0.10
  - 0.11

before_install:
  - wget http://dl.google.com/closure-compiler/compiler-latest.zip
  - unzip compiler-latest.zip -d compiler-latest
  - npm install -g gulp

script:
  - gulp
